import type { Metadata } from "next";
import { Lora as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { ToasterProvider } from "@/providers/toast-provider";
import localFont from 'next/font/local'

const fontRaleway = localFont({
  src: '../public/fonts/Raleway-SemiBold.ttf',
  display: 'swap',
  variable: "--font-raleway",
})

export const metadata: Metadata = {
  title: "Ecommerce store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontRaleway.className}>
      <body className={cn(
        "min-h-screen bg-background antialiased",
      )}>
        <ToasterProvider />
        {children}
      </body>
    </html>
  );
}
